version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - lms-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - lms-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - course-service
      - enrollment-service
      - progress-service
      - certificate-service
    networks:
      - lms-net

  course-service:
    build: ./course-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - lms-net

  enrollment-service:
    build: ./enrollment-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - lms-net

  progress-service:
    build: ./progress-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - lms-net

  certificate-service:
    build: ./certificate-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./certificates:/app/certificates
    networks:
      - lms-net

  auth-service:
    build: ./auth-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - lms-net

networks:
  lms-net:
    driver: bridge













#version: "3.8"
#
#services:
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.5.0
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: confluentinc/cp-kafka:7.5.0
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#
#  api-gateway:
#    build: ./api-gateway
#    ports:
#      - "8080:8080"
#    depends_on:
#      - auth-service
#      - course-service
#      - enrollment-service
#      - progress-service
#      - certificate-service
#
#  course-service:
#    build: ./course-service
#    ports:
#      - "8081:8081"
#    depends_on:
#      - kafka
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#
#  enrollment-service:
#    build: ./enrollment-service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - kafka
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#
#  progress-service:
#    build: ./progress-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      - kafka
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#
#  certificate-service:
#    build: ./certificate-service
#    ports:
#      - "8084:8084"
#    depends_on:
#      - kafka
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    volumes:
#      - ./certificates:/app/certificates
#
#  auth-service:
#    build: ./auth-service
#    ports:
#      - "8085:8085"
#    depends_on:
#      - kafka
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#
#
























#version: "3.8"
#
#services:
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.5.0
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: confluentinc/cp-kafka:7.5.0
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#
#  api-gateway:
#    build: ./api-gateway
#    ports:
#      - "8080:8080"
#    depends_on:
#      - auth-service
#      - course-service
#      - enrollment-service
#      - progress-service
#      - certificate-service
#
#  course-service:
#    build: ./course-service
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#
#  enrollment-service:
#    build: ./enrollment-service
#    ports:
#      - "8082:8082"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#
#
#  progress-service:
#    build: ./progress-service
#    ports:
#      - "8083:8083"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#
#  certificate-service:
#    build: ./certificate-service
#    ports:
#      - "8084:8084"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    volumes:
#      - ./certificates:/app/certificates
#
#
#
#
#  auth-service:
#    build: ./auth-service
#    container_name: auth-service
#    ports:
#      - "8085:8085"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/lms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092