server:
  port: 8080

spring:
  application:
    name: api-gateway

#  security:
#    user:
#      name: admin
#      password: tear@123
#      roles: ADMIN

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true   # ‚≠ê VERY IMPORTANT
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true





      routes:
        - id: auth-service
          uri: http://auth-service:8085
          predicates:
            - Path=/auth/**

        - id: course-service
          uri: http://course-service:8081
          predicates:
            - Path=/courses/**

        - id: enrollment-service
          uri: http://enrollment-service:8082
          predicates:
            - Path=/user/enrollments/**,/admin/enrollments/**

        - id: progress-service
          uri: http://progress-service:8083
          predicates:
            - Path=/progress/**

        - id: certificate-service
          uri: http://certificate-service:8084
          predicates:
            - Path=/certificates/**